# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCountry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SDWebImage', '~> 4.0'
pod 'ReachabilitySwift'

  # Pods for MyCountry

  target 'MyCountryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCountryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
